// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIeqzZLxN6aWh0KrAlxm70iLPGpIfnD1c',
    appId: '1:749047802790:web:6c12cde4542c9610adfd67',
    messagingSenderId: '749047802790',
    projectId: 'financy-app-803d6',
    authDomain: 'financy-app-803d6.firebaseapp.com',
    storageBucket: 'financy-app-803d6.firebasestorage.app',
    measurementId: 'G-74B2H16ET1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuioxuvMzYHr1JQAGTt4qg-NH5TwYWNRo',
    appId: '1:749047802790:android:3e2ca334a7505586adfd67',
    messagingSenderId: '749047802790',
    projectId: 'financy-app-803d6',
    storageBucket: 'financy-app-803d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrT0pAE94p8fqiw7pBi_pk0Dsm4uo2bTA',
    appId: '1:749047802790:ios:8925c49c9815885aadfd67',
    messagingSenderId: '749047802790',
    projectId: 'financy-app-803d6',
    storageBucket: 'financy-app-803d6.firebasestorage.app',
    iosBundleId: 'dev.felipe.financy.financyApp',
  );

}